plugin:
    name: 'pensoft.calendar::lang.plugin.name'
    description: 'pensoft.calendar::lang.plugin.description'
    author: Pensoft
    icon: oc-icon-calendar-o
    homepage: ''
permissions:
    pensoft.calendar.manage_entries:
        tab: 'pensoft.calendar::lang.plugin.name'
        label: 'pensoft.calendar::lang.calendar.manage_entries'
    pensoft.calendar.manage_events:
        tab: 'pensoft.calendar::lang.plugin.name'
        label: 'pensoft.calendar::lang.calendar.manage_events'
    pensoft.calendar.manage_categories:
        tab: 'pensoft.calendar::lang.plugin.name'
        label: 'pensoft.calendar::lang.calendar.manage_categories'
navigation:
    main-menu-item:
        label: 'pensoft.calendar::lang.calendar.events'
        url: pensoft/calendar/entries
        icon: icon-calendar
        sideMenu:
            side-menu-item2:
                label: 'pensoft.calendar::lang.calendar.entries'
                url: pensoft/calendar/entries
                icon: icon-bars
            side-menu-item:
                label: Types
                url: /pensoft/calendarcardsextension/eventtypes
                icon: icon-tag
